version: '3'
services:
  neo4j:
    # image: neo4j:4.1
    image: neo4j:4.2-enterprise
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./conf:/conf
      - ./data:/data
      - ./import:/import
      - ./logs:/logs
      - ./plugins:/plugins
    environment: 
      # Raise memory limits
      NEO4J_AUTH: neo4j/j4one
      NEO4J_dbms_memory_pagecache_size: 1G
      NEO4J_dbms.memory.heap.initial_size: 1G
      NEO4J_dbms_memory_heap_max__size: 1G
      NEO4J_ACCEPT_LICENSE_AGREEMENT: 'yes'

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: sp
      POSTGRES_DB: xpc
      POSTGRES_PASSWORD: VeryStrongP4ssw0rd
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: remember2changeTheP4sswd
      PGADMIN_LISTEN_PORT: 5050
    volumes:
        - ./pgadmin:/root/.pgadmin
    ports:
      - "5050:5050"
    restart: unless-stopped